const SUCCESS_CREATED = 201;
const DATA_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND = 404;
const СONFLICT_ERROR = 409;
const SERVER_ERROR = 500;

module.exports = {
  SUCCESS_CREATED,
  DATA_ERROR,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND,
  СONFLICT_ERROR,
  SERVER_ERROR,
};
